services:
  backend:
    build: ./backend
    container_name: backend-con
    volumes:
      - /home/ayush/client-driven-solutions-assignment/backend:/app
      - /app/node_modules
    ports:
      - 5000:5000
    networks:
      - app-net
  frontend:
    build: ./frontend
    container_name: frontend-con
    volumes:
      - /home/ayush/client-driven-solutions-assignment/frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - app-net
networks:
  app-net:
    driver: bridge